<div class="banners_outer">
    <div class="flexslider banners">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('buyshop_slider_banners')->toHtml() ?>
    </div>
</div>
<script type="text/javascript">
    jQuery(function(){
        jQuery('.flexslider.banners').flexslider({
            animation: "slide",
            pauseOnHover: true,
            controlNav: false,
            prevText: "<i class='icon-left-thin'></i>",
            nextText: "<i class='icon-right-thin'></i>"

        });
    })
</script>