<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
<div class="add-to-cart">
    <form id="form-add_to_cart">
        <?php if(!$_product->isGrouped()): ?>
        <div class="qty">
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input id="qty" class="input-text qty" type="text" title="Qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" maxlength="12" name="qty">
        </div>
        <?php endif; ?>
        <button class="button btn-cart" title="<?php echo $buttonTitle ?>" type="button" onClick="productAddToCartForm.submit(this)"><i class="icon-basket"></i><?php echo $buttonTitle ?></button>
    </form>
</div>
<?php endif; ?>
