<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<!-- Blog post preview -->

<?php if ($post->isViewableForVisitor()): ?>

    <div class="post-preview">
        <?php echo $this->getBeforePostContentHtml() ?>
        <h3><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h3>


        <?php if ($featuredImage = $post->getFeaturedImage()): ?>
            <div class="image"><img src="<?php echo $featuredImage->getFullSizeImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>" class="img-responsive img-rounded"/></div>
            <?php
            /*
             *  getThumbnailImage()
                getMediumImage()
                getLargeImage()
                getFullSizeImage()
                getPostThumbnailImage()
                getAvailableImage()
                getImageByType($type = 'thumbnail')
            */
            ?>
        <?php endif; ?>



        <?php echo $this->getAfterPostContentHtml() ?>

        <?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
            <?php echo $post->getPostExcerpt() ?>
        <?php else: ?>
            <?php echo $post->getPostContent() ?>
        <?php endif; ?>
    </div>
    <div class="line"></div>


<?php else: ?>
    <?php echo $this->getPasswordProtectHtml($post) ?>
<?php endif; ?>

<!-- //end Blog post preview -->