<h4><i class="icon-facebook"></i><?php echo $this->__('FACEBOOK') ?></h4>
<div class="fb_outer">

	
	
	<div class="fb_outer">
              <div id="fb-root"></div>
              <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
              <div class="fb-like-box" data-href="http://www.facebook.com/<?php echo Mage::getStoreConfig('buyshopconfig/social_accounts/facebook_profile_name')?>" data-width="292" data-height="320" data-show-faces="true" data-stream="false" data-header="false" data-border-color="#ffffff"></div>
            </div>
</div>