<?php $_helper = $this->helper('catalog/output'); ?>
<?php
    $_product = $this->getProduct();
    $widthSmall=62;
    $heightSmall=62;
    $widthMedium=460;
    $heightMedium=440;




?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<style>
<!--
body.ajax-index-options{

 padding:0px;
 margin:0px;
 /*background:url(<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail', $_product->getFile())->resize(200, 200)?>) no-repeat right top;*/
}
.product-shop .availability {
    border-bottom: 0px solid #D7D7D7;
    padding-bottom: 20px;
}
.product-shop .price-box {
    padding: 8px 0 10px;
}
-->
</style>


<form style="padding:30px 30px 0" action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
<div class="product-box quickviewblock">
    <div class="row">
        <div class="span5">
            <div class="product-img-box">
                <div class="row">

                    <div class="span6">
                        <div class="product-image">

                                <img class="product-retina" data-image2x="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail', $_product->getFile())->resize($widthMedium*2, $heightMedium*2)?>" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail', $_product->getFile())->resize($widthMedium, $heightMedium)?>" alt=""  />

                        </div>
                        <!--<div class="socialsplugins_wrapper">
                            <?php /*echo $this->getLayout()->createBlock('cms/block')->setBlockId('buyshop_social_like_buttons')->toHtml() */?>
                        </div>-->
                        <?php if(Mage::getStoreConfig('buyshoplayout/product_info/qr')):?>
                        <div class="clearfix hidden-phone" style="margin: 20px 0 0 0">
                            <img src="http://api.qrserver.com/v1/create-qr-code/?size=100x100&data=<?php echo Mage::helper("core/url")->getCurrentUrl()  ?>" alt="QR:  <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"/>
                        </div>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
        <div class="span7" style="width: 440px">
            <div class="product-shop">

                <div class="product_info_left">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>

                    <?php if(!Mage::getStoreConfig('buyshopconfig/options/catalog_mode')):?>
                    <div class="product_type_data_price"><?php echo $this->getChildHtml('product_type_data') ?></div>
                    <?php endif;?>

                    <?php if ($_product->getShortDescription()):?>
                    <div class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    <?php endif;?>

                    <?php if(!Mage::getStoreConfig('buyshopconfig/options/catalog_mode')):?>
                    <?php  echo $this->getPriceHtml($_product) ?>
                    <?php endif;?>

                    <?php echo $this->getChildHtml('alert_urls') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                    <?php echo $this->getChildHtml('extrahint') ?>



                    <?php if(!Mage::getStoreConfig('buyshopconfig/options/catalog_mode')):?>
                    <?php if (!$this->hasOptions()):?>
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                        <?php echo $this->getChildHtml('extra_buttons') ?>
                        <?php endif; ?>
                    <?php endif; ?>



                    <?php echo $this->getChildHtml('other');?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                    <?php endif;?>
                    <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                    <?php endif;?>








                </div>


            </div>
        </div>
    </div>
</div>

</form>









<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {


        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;
            if (url) {
                form.action = url;
            }
            var e = null;
            // Start of our new ajax code
            if (!url) {
                url = jQuery('#product_addtocart_form').attr('action');
            }
            url = url.replace("checkout/cart","ajax/index"); // New Code
            var data = jQuery('#product_addtocart_form').serialize();
            data += '&isAjax=1';

            try {
                jQuery.ajax( {
                    url : url,
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(data) {

                        parent.setAjaxData(data,true);
                    }
                });
            } catch (e) {
            }
            // End of our new ajax code
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }
        }
    }.bind(productAddToCartForm);
    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>